config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :mopeds do
    resources :bookings, only: [:create, :new] do
      get :confirmed
      get :declined
    end
  end
  get "my_bookings", to: "bookings#my_bookings"
  get "my_mopeds", to: "mopeds#my_mopeds"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :moped
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :start_before_end

  private

  def start_before_end
    return if end_date.blank? || start_date.blank?

    errors.add(:start_date, " cannot be later than end date.") if start_date > end_date
  end
end

app/models/moped.rb
class Moped < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :users, through: :bookings
  validates :name, :color, :description, :price, :address, presence: true
  has_one_attached :image
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :mopeds, dependent: :destroy
  has_many :bookings
  has_many :bookings, through: :mopeds

  validates :first_name, :last_name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @moped = Moped.find(params[:moped_id])
    @booking = Booking.new
  end

  def create
    @moped = Moped.find(params[:moped_id])
    @booking = Booking.new(booking_params)
    @booking.moped = @moped
    if @booking.save
      redirect_to my_bookings_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def my_bookings
    @my_bookings = Booking.where(user: current_user, confirmed: true).order(created_at: :desc)
    @my_booking_requests = Booking.where(user: current_user, confirmed: false).order(created_at: :desc)
    @my_mopeds = Moped.where(user: current_user)
  end

  def confirmed
    @moped = Moped.find(params[:moped_id])
    @booking = Booking.find(params[:booking_id])
    @booking.moped = @moped
    @booking.confirmed = true
    @booking.save
    redirect_to my_mopeds_path(current_user)
  end

  def declined
    @moped = Moped.find(params[:moped_id])
    @booking = Booking.find(params[:booking_id])
    @booking.moped = @moped
    @booking.declined = true
    @booking.save
    redirect_to my_mopeds_path(current_user)
  end
  
  private

  def booking_params
    params.require(:booking).permit(:user_id, :moped_id, :start_date, :end_date)
  end
end

app/controllers/mopeds_controller.rb
class MopedsController < ApplicationController
  def index
    @users = User.all
    @mopeds = Moped.all
    @markers = @mopeds.geocoded.map do |moped|
      {
        lat: moped.latitude,
        lng: moped.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { moped: moped }),
        marker_html: render_to_string(partial: "marker", locals: {moped: moped})
      }
    end
  end

  def show
    @moped = Moped.find(params[:id])
    @previous_moped = Moped.where("id < ?", @moped.id).last
    @next_moped = Moped.where("id > ?", @moped.id).first

    @mopeds = Moped.all
    @booking = Booking.new
    # @moped.image.attach(io: URI.open(@moped.image_url), filename: 'image.jpg') if @moped.image_url.present?
  end

  def new
    @moped = Moped.new
  end

  def create
    @moped = Moped.new(moped_params)
    if @moped.save
      redirect_to my_mopeds_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @moped = Moped.find(params[:id])
    @moped.bookings.destroy_all
    @moped.destroy
    redirect_to my_mopeds_path, status: :see_other
  end

  def edit
    @moped = Moped.find(params[:id])
  end

  def update
    @moped = Moped.find(params[:id])
    if @moped.update(moped_params)
      redirect_to moped_path(@moped)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def my_mopeds
    @my_mopeds = Moped.where(user: current_user).order(created_at: :desc)
  end

  private

  def moped_params
    params.require(:moped).permit(:name, :color, :description, :price, :address, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/my_bookings.html.erb
<br>
<br>

<div class="tab-container">
  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-bo" aria-selected="true">Pending</button>
      <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Confirmed</button>
      <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">Declined</button>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <% @my_booking_requests.each do |booking| %>
        <div class="container-booking">
          <div class="card-booking">
            <%= image_tag "#{booking.moped.image_url}", class: "moped-booking-image"%>
            <div class="card-booking-moped-infos">
              <div>
                <h2><%= booking.moped.name %></h2>
                <p>£<%= booking.moped.price %></p>
              </div>
              <div>
                <h2> Pending</h2>
                <p><%= booking.start_date%> - <%= booking.end_date %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      <% @my_bookings.each do |booking| %>
        <div class="container-booking">
          <div class="card-booking">
            <%= image_tag "#{booking.moped.image_url}", class: "moped-image"%>
            <div class="card-booking-moped-infos">
              <div>
                <h2><%= booking.moped.name %></h2>
                <p>£<%= booking.moped.price %></p>
              </div>
              <div>
                <h2><%= booking.start_date%> - <%= booking.end_date %></h2>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">...</div>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>Book this moped</h1>


<%= simple_form_for [@moped, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :moped_id, value: @moped.id %>
  <%= f.submit "Book" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Motorino</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" integrity="sha512-ELV+xyi8IhEApPS/pSj66+Jiw+sOT1Mqkzlh8ExXihe4zfqbWkxPRi8wptXIO9g73FSlhmquFlUOuMSoXz5IRw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js" integrity="sha256-lSjKY0/srUM9BE3dPm+c4fBo1dky2v27Gdjm2uoZaL0=" crossorigin="anonymous"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/mopeds/_info_window.html.erb
<br>
  <p><%= link_to moped.name, moped_path(moped) %></p>
  <p><%= moped.address %></p>
  <a href=<%="#anchor-#{moped.id}"%>>See details</a>

app/views/mopeds/_marker.html.erb
<%= image_tag "navbar-logo-yellow-circle.png", height: 30, width: 30, class:"Logo", alt: "Logo" %>

app/views/mopeds/edit.html.erb
<br>
<br>
<br>

<h1>Edit Moped</h1>
<%= form_with(model: @moped, url: moped_path(@moped), method: :patch) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>
  <div>
    <%= form.label :n_of_passengers %>
    <%= form.number_field :n_of_passengers %>
  </div>
  <div>
    <%= form.submit "Update Moped" %>
  </div>
<% end %>

app/views/mopeds/index.html.erb
<div class="map"
  style="width: 100%; height: 400px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<div class = "card-moped-container-index">
    <% @mopeds.each do |moped| %>
      <div class="card-moped-index" id=<%="anchor-#{moped.id}"%>>
        <div class="card-moped-index-infos">
        <%= image_tag "#{moped.image_url}", height: 100, class: "moped-image"%>
          <h5><%= link_to moped.name, moped_path(moped) %></h5>
          <p>Price: £<%= moped.price %></p>
          <p><%= moped.address %></p>
          <p>Owned by <%= moped.user.first_name %></p>
        </div>
      </div>
    <% end %>
</div>

app/views/mopeds/my_mopeds.html.erb
  <div class="container-header">
    <%= link_to "Add a new moped", new_moped_path, class: "btn btn-success-blue btn-new-moped" %>
  </div>

  <% @my_mopeds.each do |moped| %>
  <div class="container-my-mopeds">
    <div class="card-my-moped">
      <%= image_tag "#{moped.image_url}", class: "my-moped-image"%>
      <div class="card-my-moped-infos">
          <h3><%= moped.name %></h3>
          <p><%= link_to "Edit", edit_moped_path(moped), class: "btn btn-success-blue" %> </p>
          <p><%= link_to "Delete", moped_path(moped), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-success-blue" %></p>
      </div>
    </div>
      <div>
        <% if moped.bookings.empty? %>
          <p>No bookings yet</p>
        <% else %>
          <% moped.bookings.each do |booking|%>
          <div class="card-my-booking">
          <h4>BOOKING REQUEST</h4>
            <h5><%= booking.user.first_name %> <%= booking.user.last_name %></h5>
            <p><%= booking.start_date %> - <%= booking.end_date %></p>
            <% if booking.confirmed == false && booking.declined == false%>
            <%= link_to "Confirm Booking", moped_booking_confirmed_path(booking.moped_id, booking.id), class: "btn btn-success-small-blue" %>
            <%= link_to "Decline Booking", moped_booking_declined_path(booking.moped_id, booking.id), class: "btn btn-success-small-red" %>
            <% elsif booking.declined == true%>
            <p>Declined</p>
            <% end %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/mopeds/new.html.erb
<div class = "sign-up">

  <h1 class = "mb-2">List your moped!</h1>

  <%= simple_form_for @moped do |f| %>
    <%= f.input :name %>
    <%= f.input :color %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :address,
      input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
      wrapper_html: {data: {controller: "address-autocomplete",
      address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
    <%= f.input :n_of_passengers %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.button :submit, "Create Moped", class: "mt-1 btn-success-blue" %>
  <% end %>

</div>

app/views/mopeds/show.html.erb
<div class="container text-center">
  <div class="card moped-details mx-auto" style="max-width: 400px; border: 1px solid #ccc; border-radius: 8px; padding: 4px;">
    <div class="card-body">
      <h4 class="card-title"><%= @moped.name %></h4>

      <div class="card-booking-moped-infos">
        <!-- Information above the image -->
        <div class="row">
          <div class="col">
            <p><strong>£</strong> <%= @moped.price %> per day</p>
          </div>
        </div>

        <div class="moped-image-container">
          <%= image_tag "#{@moped.image_url}", class: "show-moped-image", width: 150, height: 150 %>
        </div>

        <!-- Information below the image -->
        <div class="row">
          <div class="col">

          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="mt-4">
    <% if @previous_moped %>
      <%= link_to "Back", moped_path(@previous_moped), class: "btn btn-success-blue" %>
    <% end %>

    <% if @next_moped %>
      <%= link_to "Next", moped_path(@next_moped), class: "btn btn-success-blue" %>
    <% end %>
    <p class="mb-0">Moped <%= @mopeds.index(@moped) + 1 %> out of <%= @mopeds.count %></p>

  </div>

  <div class="container-booking mt-4">
  <div class="card-booking" style="max-width: 250px; max-height: 300px; margin: 0 auto; border: 1px solid #ccc; border-radius: 8px; padding: 20px;">



    <div class="card-booking-moped-infos calendar-div" data-controller="datepicker" style="text-align: center;">
      <%= simple_form_for [@moped, @booking] do |f| %>
        <%= render 'shared/error', object: @booking %>
        <div style="display: flex; flex-direction: column; align-items: center;">
          <%= f.input :start_date, as: :datepicker, label: "Start Date", input_html: { class: "form-control", style: "text-align: center;" } %>
          <%= f.input :end_date, as: :datepicker, label: "End Date", input_html: { class: "form-control", style: "text-align: center;" } %>
        </div>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :moped_id, value: @moped.id %>
        <%= f.submit "Book", class: "btn btn-success-yellow" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
  <div class="banner">
  <div class="banner-content">
    <div class="banner-info">
      <div>
        <%= image_tag "logo-yellow.jpg", height: 300, class: "logo-image"%>
      </div>
      <div class="banner-taglines">
        <h2>Rent a moped.</h2>
        <h2>Beat the traffic. </h2>
        <h2>Ride like a local. </h2>
      </div>
    </div>
    <div class="banner-links">
      <div class="banner-link-1">
        <%= link_to "Find a moped", mopeds_path, class: "btn btn-success-blue" %>
      </div>
      <div class="banner-link-2">
        <%= link_to "List a moped", new_moped_path(current_user), class: "btn btn-success-blue" %>
    </div>
    </div>
    </div>
  </div>

app/views/shared/_error.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-error">
            The form contains <%= pluralize(object.errors.count, "error") %>.
        </div>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
              <li>* <%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#">FAQs</a>
    <a href="#">About</a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Motorino©️
  </div>
</div>

app/views/shared/_my_booking.html.erb
<div class="container">
      <div class="card-booking">
        <img src="/open-component/images/vespa.jpg"/>
        <div class="card-booking-moped-infos">
          <div>
            <h2><%= booking.moped.name %></h2>
            <p><%= booking.moped.description %></p>
          </div>
          <div>
            <h2><%= booking.start_date%> - <%= booking.end_date %></h2>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
     <div class ="logo"></div>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <div class="btn-home">
              <%= link_to "Home", root_path, class: "btn btn-success-yellow" %>
            </div>
          </li>
          <li class="nav-item active">
            <div class="btn-mybookings">
              <%= link_to "My Bookings", my_bookings_path, class: "btn btn-success-yellow" %>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "orietta.png", class:"orietta", alt:"dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My mopeds", my_mopeds_path, class: "dropdown-item" %>
              <%= link_to "Help", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <% else %>
          <li class="nav-item">
          <div class="btn-home">
            <%= link_to "Login", new_user_session_path, class: "btn btn-success-yellow" %>
          </div>
          </li>
          <li class="nav-item">
            <div class="btn-home">
              <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success-yellow" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>